version: "3.7"
name: liferay-automatic-order-flow
services:
  laof-liferay:
    image: liferay/dxp:2024.q1.5
    container_name: laof-liferay
    depends_on:
      laof-bdd:
        condition: service_healthy
    environment:
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_DELAY: 10
      LIFERAY_RETRY_PERIOD_JDBC_PERIOD_ON_PERIOD_STARTUP_PERIOD_MAX_PERIOD_RETRIES: 10
      LIFERAY_JVM_OPTS: "-Xms2560m -Xmx4096m"
      # Used by .config files to create client extensions as remote apps in Liferay Control Panel
    networks: 
      - laof-network
    ports: 
      - 8080:8080
      - 127.0.0.1:11311:11311
    volumes:
      - ./liferay-74/mount:/mnt/liferay
      - laof-liferay-tools:/opt/liferay/tools
      - laof-liferay-data:/opt/liferay/data
      - laof-liferay-osgi-configs:/opt/liferay/osgi/configs
      - laof-liferay-osgi-marketplace:/opt/liferay/osgi/marketplace
      - laof-liferay-osgi-modules:/opt/liferay/osgi/modules
      - laof-liferay-osgi-war:/opt/liferay/osgi/war
      
  laof-bdd:
    container_name: laof-mysql
    networks:
      - laof-network
    image: mysql:8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: lportal
      MYSQL_USER: liferay
      MYSQL_PASSWORD: liferay
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - laof-mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s
      
  laof-flowise:
    image: flowiseai/flowise:1.8.2
    restart: always
    entrypoint: /bin/sh -c "sleep 3; flowise start"
    container_name: flowiseai
    networks:
      - laof-network
    hostname: laof-flowise
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000
    ports:
      - 3000:3000
    volumes:
      - ./flowiseai:/root/.flowise
    environment:
      DEBUG: false
      PORT: 3000
      FLOWISE_USERNAME: inetumuser
      FLOWISE_PASSWORD: inetumpass
      FLOWISE_SECRETKEY_OVERWRITE: inetumpass
      APIKEY_PATH: /root/.flowise
      SECRETKEY_PATH: /root/.flowise
      LOG_LEVEL: info
      LOG_PATH: /root/.flowise/logs
      DATABASE_TYPE: sqlite
      DATABASE_PATH: /root/.flowise
  laof-n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: laof-n8n
    networks:
      - laof-network
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=Inetum2024
      - NODE_ENV=production
      - N8N_BASIC_AUTH_USER=demo@inetum.com
      - N8N_BASIC_AUTH_PASSWORD=Inetum2024
    volumes:
      - laof-n8n:/home/node/.n8n
      - ./n8n/database.sqlite:/home/node/.n8n/database.sqlite
networks:
  laof-network:
    name: laof-network
volumes:
  laof-liferay-data:
  laof-liferay-tools:
  laof-liferay-osgi-configs:
  laof-liferay-osgi-marketplace:
  laof-liferay-osgi-modules:
  laof-liferay-osgi-war:
  laof-mysql:
  laof-n8n:
